language: node_js
node_js:
  - "16"
cache:
  directories:
    - "node_modules"
    - "$HOME/.npm"
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
  skip_cleanup: true
